[project]
name = "custom-photo-qr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.0.0",
    "qrcode-artistic>=3.0.2",
    "segno>=1.6.6",
    "streamlit>=1.51.0",
]
