name: SLSA L3 Build (Modern Way)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  

env:
  IMAGE_NAME: taha2samy/qr-maker-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_password }}

      - name: Build and Push
        uses: docker/bake-action@v5 
        id: bake                     
        with:
          files: ./docker-bake.hcl
          push: true
      - name: Extract Digest
        id: extract
        run: |
          DIGEST=$(echo '${{ steps.bake.outputs.metadata }}' | jq -r '."app"."containerimage.digest"')
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_OUTPUT
          echo "Extracted Digest: $DIGEST"

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.extract.outputs.IMAGE_DIGEST }}
          push-to-registry: true
